<div class="panel panel-primary" style="margin: 150px auto; width: 400px">
	<div class="panel-heading">
		<h4>
			<i class="glyphicon glyphicon-user"></i>
			Login to your account
		</h4>
	</div>
	<div class="panel-body">
		<div class="text-center">
			<?= $this->messenger; ?>
		</div>	
		<?= $this->data['formLogin']; ?>
		<div class="alert alert-warning" style="margin-bottom: 0px; margin-top: 20px">
			<div><strong>Hint for the reviewer</strong></div>
			<div>Username: admin</div>
			<div>Password: pass123</div>
		</div>
	</div>
</div>